name: "🐞 バグ報告 (Bug Report)"
description: "バグを報告する場合はこちらから"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **バグを報告いただきありがとうございます！**
        必要な情報を記入し、再現可能な手順を記載してください。

  - type: dropdown
    id: section
    attributes:
      label: 問題が発生しているソフトウェア
      options:
        - Orizm Console
        - CMS
        - Consumer
        - Starter
        - Docs
        - Other
    validations:
      required: true

  - type: input
    id: orizm-version
    attributes:
      label: "バージョン情報"
      description: "(あれば) 使用しているSDKバージョンや、Starterバージョンを記入してください。"
      placeholder: "例: cms-sdk@1.2.3"

  - type: textarea
    id: bug-description
    attributes:
      label: "バグの概要"
      description: "発生した問題の内容を簡潔に説明してください。"
      placeholder: "例: データの更新に失敗する"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "再現手順"
      description: "バグを再現する手順や、コードを記入してください。"
      placeholder: ""
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "期待する動作"
      description: "本来どのように動作するべきかを記入してください。"
      placeholder: "例: エラーが発生しないこと"

  - type: textarea
    id: error-messages
    attributes:
      label: "エラーメッセージ・スクリーンショット"
      description: "エラーメッセージやスクリーンショットを添付してください（任意）。"
      placeholder: "エラーログや画像をここに貼り付けてください。"

  - type: textarea
    id: additional-info
    attributes:
      label: "補足情報"
      description: "その他、参考になりそうな情報を記入してください（任意）。"
